HospitalManagementSystem/Areas/Admin/Controllers/ContactController.cs
using HospitalServices.Interfaces;
using Microsoft.AspNetCore.Mvc;
using ViewModels;

namespace HospitalManagementSystem.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("Contacts")]
    public class ContactController : Controller
    {
        private readonly IContacts _contact;
        public ContactController(IContacts contact)
        {
            _contact = contact;
        }

        [Route("contacts")]
        public IActionResult Index(int pageNumber = 1, int pageSize = 10)
        {
            return View(_contact.GetAllContacts(pageNumber, pageSize));
        }

        [HttpGet]
        [Route("update")]
        public IActionResult Edit(Guid id)
        {
            ContactViewModel model = _contact.GetContact(id);
            return View(model);
        }

        [HttpPost]
        [Route("update")]
        public IActionResult Edit(ContactViewModel model)
        {

            _contact.UpdateContact(model);
            return RedirectToAction("Index");
        }

        [HttpGet]
        [Route("Add")]
        public IActionResult Add()
        {

            return View(new ContactViewModel());

        }

        [HttpPost]
        [Route("Add")]
        public IActionResult Add(ContactViewModel model)
        {
            _contact.AddContact(model);
            return RedirectToAction("Index");

        }

        [Route("Delete")]
        public IActionResult Delete(Guid id)
        {
            _contact.RemoveContact(id);
            return RedirectToAction("Index");
        }
    }
}

HospitalManagementSystem/Areas/Admin/Controllers/HospitalController.cs
using HospitalServices.Interfaces;
using Microsoft.AspNetCore.Mvc;
using ViewModels;
using Utilities;
using HospitalModels;

namespace HospitalManagementSystem.Areas.Admin.Controllers
{
      [Area("Admin")]
    [Route("hosital")]
    public class HospitalController : Controller
    {
        private readonly IHospitalProp _hospital;
        public HospitalController(IHospitalProp hospital)
        {
            _hospital = hospital;
        }

        [Route("/")]
        public IActionResult Index(int pageNumber=1, int pageSize=10)
        {
            return View(_hospital.GetAll(pageNumber,pageSize));
        }

        [HttpGet]
        [Route("Edit")]
        public IActionResult Edit(Guid id) {
            HospitalViewModel model = _hospital.GetHospitalViewModel(id);
            return View(model);
        }

        [HttpPost]
        [Route("Edit")]
        public IActionResult Edit(HospitalViewModel model)
        {
            
             _hospital.UpdateHospital(model);
            return RedirectToAction("Index");
        }

        [HttpGet]
        [Route("create")]
        public IActionResult Add()
        {
            
            return View(new HospitalViewModel());

        }

        [HttpPost]
        [Route("create")]
        public IActionResult Add(HospitalViewModel model)
        {
            _hospital.InsertNewHospital(model);
            return RedirectToAction("Index");

        }

        [Route("Delete")]
        public IActionResult Delete(Guid id)
        {
            _hospital.DeleteHospitalView(id);
            return RedirectToAction("Index");   
        }


    }
}

HospitalManagementSystem/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HospitalManagementSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HospitalManagementSystem.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/HomeIndex">HospitalManagementSystem</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/HomeIndex">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Hospital" asp-action="Index">Hospitals</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Room" asp-action="Index">Rooms</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Contact" asp-action="Index">Contacts</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - HospitalManagementSystem - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>